name: Run Unit & E2E Tests

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "include/**"
      - "tests/**"
      - "CMakeLists.txt"
      - ".github/workflows/ci-tests.yml"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "include/**"
      - "tests/**"
      - "CMakeLists.txt"
      - ".github/workflows/ci-tests.yml"


jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Build and Run Tests
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build --target cqq_unit_tests cqq_e2e_tests
          ctest --test-dir build --output-on-failure
