name: CodSpeed Benchmarking

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "include/**"
      - "benchmarks/**"
      - "CMakeLists.txt"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "include/**"
      - "benchmarks/**"
      - "CMakeLists.txt"

permissions:
  pull-requests: write
  contents: read
  id-token: write

jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Benchmarks
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCODSPEED_MODE=simulation
          cmake --build build --target cqq_benchmarks

      - name: Run CodSpeed
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: ./build/cqq_benchmarks
